server/server/apps/course/urls.py
from django.urls import path

from . import views

app_name = "course"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:course_url>", views.show, name="show"),
    path("<str:course_url>/approve/<int:doc_id>", views.approve, name="approve"),
    path("<str:course_url>/remove/<int:doc_id>", views.remove, name="remove"),
    path("<str:course_url>/undelete/<int:doc_id>", views.undelete, name="undelete"),
]

server/server/apps/files/urls.py
from django.urls import path

from . import views

app_name = "file"

urlpatterns = [
    path("", views.upload_file, name="upload"),
]

server/server/apps/mod/urls.py
from django.urls import path

from . import views

app_name = "mod"

urlpatterns = [
    path("", views.dashboard, name="dash"),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

from .apps.auth import views as auth_views
from .apps.content import views as content_views
from .apps.course import views as course_views
from .apps.mod import views as mod_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.login, name="login"),
    path('logout/', auth_views.logout, name="logout"),
    path('courses/', include("server.apps.course.urls", namespace="courses")),
    path('mod/', include("server.apps.mod.urls", namespace="mod")),
    path('file/', include("server.apps.files.urls", namespace="file")),
    path('', content_views.index, name="index"),
]

server/server/apps/content/models.py
from django.db import models

# Create your models here.

server/server/apps/course/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    url = models.CharField(max_length=20, unique=True)
    
    
    unapproved_files = models.ManyToManyField("files.File", related_name="classes_unap", blank=True)
    files = models.ManyToManyField("files.File", related_name="classes", blank=True)
    rejected_files = models.ManyToManyField("files.File", related_name="classes_reject", blank=True)
    
    def __str__(self):
        return self.name
    

server/server/apps/files/models.py
from django.db import models
from django.utils.text import slugify
from uuid import uuid4
from time import strftime

# Create your models here.
def gen_filename(instance, filename):
    return "upload_{0}_{1}_{2}.{3}".format(strftime('%Y-%m-%d-%H-%M%S'), uuid4(), slugify(instance.name), filename.split('.')[-1])

class File(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    
    
    uploader = models.CharField(max_length=100)
    
    payload = models.FileField(blank=True, upload_to=gen_filename)
    
    def __str__(self):
        return self.name

server/server/apps/mod/models.py
from django.db import models

# Create your models here.

class Moderator(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=16, unique=True)
    admin = models.BooleanField(default=False)
    
    classes = models.ManyToManyField("course.Course", related_name="mods", blank=True)
    
    def __str__(self):
        return self.username

server/server/apps/files/forms.py
from django import forms

from .models import File

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ["name", "payload"]

server/server/apps/content/views.py
from django.shortcuts import render
from django.conf import settings

from ..decorators import login
from ..mod.models import Moderator

# Create your views here.

@login    
def index(request):
        
    is_mod = Moderator.objects.filter(username=request.session['user']).count() > 0
    
    return render(request, 'index.html', { 'user': request.session['user'], 'is_mod': is_mod} )

server/server/apps/course/views.py
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import PermissionDenied

from django.http import Http404

from .models import Course
from ..mod.models import Moderator
from ..files.models import File

from ..decorators import login

# Create your views here.

@login
def index(request):
    courses = Course.objects.all()
    
    return render(request, 'class/index.html', {'classes': courses})
    
@login
def show(request, course_url):
    course = get_object_or_404(Course, url=course_url)

    is_mod = False

    try:
        mod = Moderator.objects.get(username=request.session['user'])
    except Moderator.DoesNotExist:
        is_mod = False
        return render(request, 'class/show.html', {'course': course, 'is_mod': is_mod})
        
    if mod.admin:
        is_mod = True
        
    elif course in mod.classes.all():
        is_mod = True
    
    return render(request, 'class/show.html', {'course': course, 'is_mod': is_mod})
    
@login
def approve(request, course_url, doc_id):
    course = get_object_or_404(Course, url=course_url)
    try:
        mod = Moderator.objects.get(username=request.session['user'])
    except Moderator.DoesNotExist:
        raise PermissionDenied

    if mod.admin or (course in mod.classes.all()):
        try:
            doc = course.unapproved_files.get(id=doc_id)
        except File.DoesNotExist:
            try:
                doc = course.files.get(id=doc_id)
            except File.DoesNotExist:
                raise Http404("Error: Document Not Related to this Course")
            raise Http404("Error: Document Already Approved")
        course.unapproved_files.remove(doc)
        course.files.add(doc)
        
        return render(request, 'class/approve.html', {'doc': doc, 'course': course})
    else:
        raise PermissionDenied 

@login
def remove(request, course_url, doc_id):
    course = get_object_or_404(Course, url=course_url)
    try:
        mod = Moderator.objects.get(username=request.session['user'])
    except Moderator.DoesNotExist:
        raise PermissionDenied
        
    if mod.admin or (course in mod.classes.all()):
        try:
            doc = course.files.get(id=doc_id)
        except File.DoesNotExist:
            try:
                doc = course.unapproved_files.get(id=doc_id)
            except File.DoesNotExist:
                raise Http404("Error: Document Not Related to this Course")

            course.unapproved_files.remove(doc)
            course.rejected_files.add(doc)
            
            return render(request, 'class/remove.html', {'doc': doc, 'course': course})

        course.files.remove(doc)
        course.rejected_files.add(doc)
        
        return render(request, 'class/remove.html', {'doc': doc, 'course': course})
    else:
        raise PermissionDenied 
        
@login
def undelete(request, course_url, doc_id):
    course = get_object_or_404(Course, url=course_url)
    try:
        mod = Moderator.objects.get(username=request.session['user'])
    except Moderator.DoesNotExist:
        raise PermissionDenied
        
    if mod.admin or (course in mod.classes.all()):
        try:
            doc = course.rejected_files.get(id=doc_id)
        except File.DoesNotExist:
            raise Http404("Error: Document Not Related to this Course")

        course.rejected_files.remove(doc)
        course.files.add(doc)
        
        return render(request, 'class/undelete.html', {'doc': doc, 'course': course})
    else:
        raise PermissionDenied 

server/server/apps/files/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .forms import UploadFileForm
from .models import File
from ..decorators import login

# Create your views here.
@login
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            inst = File(name=request.POST['title'] , payload=request.FILES['file'])
            inst.save()
            return HttpResponseRedirect('/upload/success')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form':form})

server/server/apps/mod/views.py
from django.shortcuts import render, get_object_or_404

from .models import Moderator
from ..course.models import Course

from ..decorators import login
# Create your views here.

@login
def dashboard(request):
    try:
        mod = Moderator.objects.get(username=request.session['user'])
    except Moderator.DoesNotExist:
        return render(request, 'mod/not_mod.html', {'user': request.session['user']})
        
    classes = mod.classes.all()
    if mod.admin:
        classes = Course.objects.all()
    
    if not classes:
        return render(request, 'mod/not_mod.html', {'user': request.session['user']})
    
    return render(request, 'mod/index.html', {'user': request.session['user'], 'classes': classes})
    

server/server/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>TJHSST</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">

        
        {% block head %}{% endblock %}
    </head>
    <body class="w-full" style="font-family: 'Open Sans';">
        {% block root %}
            <div class="md:w-3/4 w-full mx-auto px-4 py-8" id="root">
                {% block body %}{% endblock %}
            </div>
        {% endblock %}
    </body>
</html>

server/server/templates/class/approve.html
{% extends 'base.html' %}
{% block body %}
    Success. You have Approved {{ doc.name }} by {{ doc.uploader }} <a href="{{ doc.payload.url }}">Download</a> for the Course <a href="{% url 'courses:show' course.url %}">{{ course.name }}</a>.
{% endblock %}

server/server/templates/class/index.html
{% extends 'base.html' %}
{% block body %}
<div class="header">
	<h1>Classes</h1>
</div>
<div class="main">
    {% for class in classes %}
        <div>
            <a href="{% url 'courses:show' class.url %}">{{class.name}}</a>
            <p>{{ class.files.all|length }} Document</p>
        </div>
    {% endfor %}
</div>

{% endblock %}

server/server/templates/class/remove.html
{% extends 'base.html' %}
{% block body %}
    Success. You have Removed {{ doc.name }} by {{ doc.uploader }} <a href="{{ doc.payload.url }}">Download</a> for the Course <a href="{% url 'courses:show' course.url %}">{{ course.name }}</a>.
{% endblock %}

server/server/templates/class/show.html
{% extends 'base.html' %}
{% block head %}
<style>
    .unapproved {
        border: 5px;
        border-color: blue;
        border-style: solid;
    }
    .removed {
        border: 5px;
        border-color: red;
        border-style: solid;
    }
</style>

{% endblock %}
{% block body %}
<div class="header">
	<h1>{{ course.name }}</h1>
</div>
<div class="main">
    {% if is_mod %}
        <h3>You have moderator permissions on this course, which means you can approve of reject uploaded files.</h3>
    {% endif %}
    {% for doc in course.files.all %}
        <div>
            <h3>{{ doc.name }}</h3>
            <a href="{{ doc.payload.url }}">Download</a>
            <p>Uploaded By {{ doc.uploader }}</p>
            {% if is_mod %}
                <a href="{% url 'courses:remove' course_url=course.url doc_id=doc.id %}">REMOVE</a>
            {% endif %}
        </div>
    {% endfor %}
    
    {% if is_mod %}
        {% for doc in course.unapproved_files.all %}
            <div class='unapproved'>
                <h3>UNAPPROVED</h3>
                <h3>{{ doc.name }}</h3>
                <a href="{{ doc.payload.url }}">Download</a>
                <p>Uploaded By {{ doc.uploader }}</p>
                <a href="{% url 'courses:approve' course_url=course.url doc_id=doc.id %}">APPROVE</a>
                <a href="{% url 'courses:remove' course_url=course.url doc_id=doc.id %}">REMOVE</a>
            </div>
        {% endfor %}
        {% for doc in course.rejected_files.all %}
            <div class='removed'>
                <h3>UNAPPROVED</h3>
                <h3>{{ doc.name }}</h3>
                <a href="{{ doc.payload.url }}">Download</a>
                <p>Uploaded By {{ doc.uploader }}</p>
                <a href="{% url 'courses:undelete' course_url=course.url doc_id=doc.id %}">UNDELETE</a>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% endblock %}

server/server/templates/class/undelete.html
{% extends 'base.html' %}
{% block body %}
    Success. You have Restored {{ doc.name }} by {{ doc.uploader }} <a href="{{ doc.payload.url }}">Download</a> for the Course <a href="{% url 'courses:show' course.url %}">{{ course.name }}</a>.
{% endblock %}

server/server/templates/disallow.html
{% extends 'base.html' %}
{% block body %}
<div class="header">
	<h1>Study Bank</h1>
</div>
<div class="main">
	<div class="login-box">
		<p>You are not logged in. Please login with Ion to proceed.</p>
		<center>
			<b>{{ message }}</b><br />
			<a href="{% url 'login' %}" class="button">
				Log In with Ion
			</a>
		</center>
	</div>
</div>

{% endblock %}

server/server/templates/index.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-4xl font-bold">Study Bank</h1>
    <h3> Welcome, {{ user }}</h3>
    {% if is_mod %}
        <p><a href='{% url 'mod:dash' %}'>Moderator Dashboard</a></p>
    {% endif %}
        <p><a href='{% url 'course:index' %}'>View Courses</a></p>
{% endblock %}

server/server/templates/mod/index.html
{% extends 'base.html' %}
{% block head %}
<style>
    .unapproved {
        border: 5px;
        border-color: blue;
        border-style: solid;
    }
    .removed {
        border: 5px;
        border-color: red;
        border-style: solid;
    }
</style>

{% endblock %}
{% block body %}
<div class="header">
    <h1>Classes Moderated by {{ user }}</h1>
</div>
<div class="main">

    {% for class in classes %}
        <div>
            <a href="{% url 'courses:show' class.url %}">{{class.name}}</a>
            <p>{{ class.files.all|length }} Document</p>
            {% for doc in class.unapproved_files.all %}
                <div class='unapproved'>
                    <h3>UNAPPROVED</h3>
                    <h3>{{ doc.name }}</h3>
                    <a href="{{ doc.payload.url }}">Download</a>
                    <p>Uploaded By {{ doc.uploader }}</p>
                    <a href="{% url 'courses:approve' course_url=class.url doc_id=doc.id %}">APPROVE</a>
                    <a href="{% url 'courses:remove' course_url=class.url doc_id=doc.id %}">REMOVE</a>
                </div>
            {% endfor %}
            {% for doc in class.rejected_files.all %}
                <div class='removed'>
                    <h3>UNAPPROVED</h3>
                    <h3>{{ doc.name }}</h3>
                    <a href="{{ doc.payload.url }}">Download</a>
                    <p>Uploaded By {{ doc.uploader }}</p>
                    <a href="{% url 'courses:undelete' course_url=class.url doc_id=doc.id %}">UNDELETE</a>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>

{% endblock %}

server/server/templates/mod/not_mod.html
{% extends 'base.html' %}
{% block body %}
<div class="header">
	<h1>Access Denied</h1>
</div>
<div class="main">
    <p>Sorry, {{ user }}, but you do not have moderator permissions over any sites.</p>
</div>

{% endblock %}